### ISSUE TITLE
Fazer Form Efetuar Login

### ISSUE THREAD

**Issue by RubenOlivera** [RubenOlivera/PMSTrabalho#20]
**Form Efetuar Login**

O form efetuar login será a parte gráfica que surge no ecrã quando o Administrador de Sistema pretende aceder aos sistema. Este form pertence ao modulo "Validar Registo de Login Utilizador".

![efetuarloginvs](https://cloud.githubusercontent.com/assets/26446367/25458462/e1d50aa4-2ad1-11e7-8651-bf2c7e7bbe92.JPG)

**Comment by SRISCAC** [comment]
Após analise optou-se por alterar o Form de Login, retirando a possibilidade de se efetuar a recuperação de Login.

**Comment by SRISCAC** [comment]
![efetuarloginsemrecuperacao](https://cloud.githubusercontent.com/assets/26446367/25687277/ffe49e6a-306c-11e7-8705-261214cb4e63.JPG)

**Comment by SRISCAC** [comment]
Apos analise optou-se por retirar a possibilidade de se efetuar recuperação de password. 


![efetuarloginsemrecuperacao](https://cloud.githubusercontent.com/assets/26446367/25687304/293afcb4-306d-11e7-80a3-3c589a61e197.JPG)
